import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
import { Poppins } from "next/font/google";
import Topbar from "./Components/LandingSections/Topbar/Topbar";
import Nav from "./Components/LandingSections/Nav/Nav";
import FooterSection from "./Components/LandingSections/FooterSection/FooterSection";

const poppinsFont = Poppins({
  weight: ["200", "400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Queleads CRM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppinsFont.className}`}>
        <Topbar />
        <Nav />
        {children}
        <FooterSection />
      </body>
    </html>
  );
}
