import Images from "../../images";

export const tabMenuList = [
  {
    id: 1,
    icon: Images.LeadScan,
    name: "LeadsScan",
    isActive: false,
    image: Images.tabImage1,
    title1: "Leads to Conversion:",
    title2: "One Platform, Total Control!",
    desc: `Effortlessly generate and gather leads from multiple sources, all in one platform`,
  },
  {
    id: 2,
    icon: Images.Collableads,
    name: "CollabLeads",
    isActive: false,
    image: Images.tabImage2,
    title1: "Collaborate",
    title2: "via WhatsApp, Email, and Calls.",
    desc: `Connect with Leads via Whatsapp, Email or Phone Call in one platform with all the Lead information in front of you`,
  },
  {
    id: 3,
    icon: Images.Taskmastery,
    name: "Task Mastery",
    isActive: false,
    image: Images.tabImage3,
    title1: "Plan your work",
    title2: "and manage your sales force.",
    desc: `Assign tasks, schedule on calendar and get live notifications for every task.`,
  },
  {
    id: 4,
    icon: Images.Planalyze,
    name: "Planalyze",
    isActive: false,
    image: Images.tabImage4,
    title1: "Plan better",
    title2: "using Calendar.",
    desc: ` Get notifications of every task and pre-notifications of deadlines.`,
  },
  {
    id: 5,
    icon: Images.Teamcraft,
    name: "TeamCraft",
    isActive: false,
    image: Images.tabImage5,
    title1: "Manage",
    title2: "your own team.",
    desc: `Manage your sales force and admins for easy tracking. 
`,
  },
];
